name=FelixTheCatLED
version=1.0.1
author=Felix Ochoa
maintainer=Felix Ochoa
sentence=A lightweight Arduino library for simple LED control.
paragraph=This library provides simple methods to control LEDs.
category=Signal Input/Output
url=https://github.com/felixthecat8a/FelixTheCatLED
architectures=*
includes=FelixTheCatLED.h
